### ISSUE TITLE
ZenithProxy having proirity over every command and getting randomly frequently kicked

### ISSUE THREAD

**Issue by Jklocal** [rfresh2/ZenithProxy#85]
Hello, so I downloaded ZenithProxy and I wasn't having any issues with it until a few weeks later I logged on Minecraft using Zenith, every command I typed was having ZenithProxy responding to it
So for example if I typed /ping, It would say, [ZenithProxy] Unknown Command.
Also I've been getting kicked from the proxy with the error,
java.net.SocketException: Connection reset
Hope anyone could help me with two of these issues

**Comment by rfresh2** [comment]
> every command I typed was having ZenithProxy responding to it
So for example if I typed /ping, It would say, [ZenithProxy] Unknown Command.

2.7.1 changes the default value of replacing server commands to off so that should be resolved now

> Also I've been getting kicked from the proxy with the error,
java.net.SocketException: Connection reset

this disconnect means there's an internet connectivity issue either on your side or the MC server (i.e. 2b2t)

there's nothing that can be done in zenith about that

**Comment by Jklocal** [comment]
i love u
